/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthRouteRouteImport } from './routes/_unauth/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthPasswordResetIndexRouteImport } from './routes/_unauth/password-reset/index'
import { Route as UnauthPasswordForgotIndexRouteImport } from './routes/_unauth/password-forgot/index'
import { Route as UnauthLoginIndexRouteImport } from './routes/_unauth/login/index'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthRoomsIndexRouteImport } from './routes/_auth/rooms/index'
import { Route as AuthOfficeAttendanceIndexRouteImport } from './routes/_auth/office-attendance/index'
import { Route as AuthEventsIndexRouteImport } from './routes/_auth/events/index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'

const UnauthRouteRoute = UnauthRouteRouteImport.update({
  id: '/_unauth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthPasswordResetIndexRoute =
  UnauthPasswordResetIndexRouteImport.update({
    id: '/password-reset/',
    path: '/password-reset/',
    getParentRoute: () => UnauthRouteRoute,
  } as any)
const UnauthPasswordForgotIndexRoute =
  UnauthPasswordForgotIndexRouteImport.update({
    id: '/password-forgot/',
    path: '/password-forgot/',
    getParentRoute: () => UnauthRouteRoute,
  } as any)
const UnauthLoginIndexRoute = UnauthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => UnauthRouteRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRoomsIndexRoute = AuthRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOfficeAttendanceIndexRoute =
  AuthOfficeAttendanceIndexRouteImport.update({
    id: '/office-attendance/',
    path: '/office-attendance/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEventsIndexRoute = AuthEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthAdminIndexRoute
  '/events': typeof AuthEventsIndexRoute
  '/office-attendance': typeof AuthOfficeAttendanceIndexRoute
  '/rooms': typeof AuthRoomsIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/login': typeof UnauthLoginIndexRoute
  '/password-forgot': typeof UnauthPasswordForgotIndexRoute
  '/password-reset': typeof UnauthPasswordResetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthAdminIndexRoute
  '/events': typeof AuthEventsIndexRoute
  '/office-attendance': typeof AuthOfficeAttendanceIndexRoute
  '/rooms': typeof AuthRoomsIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/login': typeof UnauthLoginIndexRoute
  '/password-forgot': typeof UnauthPasswordForgotIndexRoute
  '/password-reset': typeof UnauthPasswordResetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_unauth': typeof UnauthRouteRouteWithChildren
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/events/': typeof AuthEventsIndexRoute
  '/_auth/office-attendance/': typeof AuthOfficeAttendanceIndexRoute
  '/_auth/rooms/': typeof AuthRoomsIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_unauth/login/': typeof UnauthLoginIndexRoute
  '/_unauth/password-forgot/': typeof UnauthPasswordForgotIndexRoute
  '/_unauth/password-reset/': typeof UnauthPasswordResetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/events'
    | '/office-attendance'
    | '/rooms'
    | '/users'
    | '/login'
    | '/password-forgot'
    | '/password-reset'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/events'
    | '/office-attendance'
    | '/rooms'
    | '/users'
    | '/login'
    | '/password-forgot'
    | '/password-reset'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_unauth'
    | '/_auth/admin/'
    | '/_auth/events/'
    | '/_auth/office-attendance/'
    | '/_auth/rooms/'
    | '/_auth/users/'
    | '/_unauth/login/'
    | '/_unauth/password-forgot/'
    | '/_unauth/password-reset/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  UnauthRouteRoute: typeof UnauthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauth': {
      id: '/_unauth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauth/password-reset/': {
      id: '/_unauth/password-reset/'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof UnauthPasswordResetIndexRouteImport
      parentRoute: typeof UnauthRouteRoute
    }
    '/_unauth/password-forgot/': {
      id: '/_unauth/password-forgot/'
      path: '/password-forgot'
      fullPath: '/password-forgot'
      preLoaderRoute: typeof UnauthPasswordForgotIndexRouteImport
      parentRoute: typeof UnauthRouteRoute
    }
    '/_unauth/login/': {
      id: '/_unauth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthLoginIndexRouteImport
      parentRoute: typeof UnauthRouteRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/rooms/': {
      id: '/_auth/rooms/'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthRoomsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/office-attendance/': {
      id: '/_auth/office-attendance/'
      path: '/office-attendance'
      fullPath: '/office-attendance'
      preLoaderRoute: typeof AuthOfficeAttendanceIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/events/': {
      id: '/_auth/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthEventsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
  AuthEventsIndexRoute: typeof AuthEventsIndexRoute
  AuthOfficeAttendanceIndexRoute: typeof AuthOfficeAttendanceIndexRoute
  AuthRoomsIndexRoute: typeof AuthRoomsIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthEventsIndexRoute: AuthEventsIndexRoute,
  AuthOfficeAttendanceIndexRoute: AuthOfficeAttendanceIndexRoute,
  AuthRoomsIndexRoute: AuthRoomsIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface UnauthRouteRouteChildren {
  UnauthLoginIndexRoute: typeof UnauthLoginIndexRoute
  UnauthPasswordForgotIndexRoute: typeof UnauthPasswordForgotIndexRoute
  UnauthPasswordResetIndexRoute: typeof UnauthPasswordResetIndexRoute
}

const UnauthRouteRouteChildren: UnauthRouteRouteChildren = {
  UnauthLoginIndexRoute: UnauthLoginIndexRoute,
  UnauthPasswordForgotIndexRoute: UnauthPasswordForgotIndexRoute,
  UnauthPasswordResetIndexRoute: UnauthPasswordResetIndexRoute,
}

const UnauthRouteRouteWithChildren = UnauthRouteRoute._addFileChildren(
  UnauthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  UnauthRouteRoute: UnauthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
