/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthRouteRouteImport } from './routes/_unauth/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthRegisterIndexRouteImport } from './routes/_unauth/register/index'
import { Route as UnauthPasswordResetIndexRouteImport } from './routes/_unauth/password-reset/index'
import { Route as UnauthLoginIndexRouteImport } from './routes/_unauth/login/index'
import { Route as AuthRoomsIndexRouteImport } from './routes/_auth/rooms/index'
import { Route as AuthProfileIndexRouteImport } from './routes/_auth/profile/index'
import { Route as AuthOfficeAttendanceIndexRouteImport } from './routes/_auth/office-attendance/index'
import { Route as AuthEventsIndexRouteImport } from './routes/_auth/events/index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthEventsEventIdIndexRouteImport } from './routes/_auth/events/$eventId/index'

const UnauthRouteRoute = UnauthRouteRouteImport.update({
  id: '/_unauth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthRegisterIndexRoute = UnauthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => UnauthRouteRoute,
} as any)
const UnauthPasswordResetIndexRoute =
  UnauthPasswordResetIndexRouteImport.update({
    id: '/password-reset/',
    path: '/password-reset/',
    getParentRoute: () => UnauthRouteRoute,
  } as any)
const UnauthLoginIndexRoute = UnauthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => UnauthRouteRoute,
} as any)
const AuthRoomsIndexRoute = AuthRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthProfileIndexRoute = AuthProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOfficeAttendanceIndexRoute =
  AuthOfficeAttendanceIndexRouteImport.update({
    id: '/office-attendance/',
    path: '/office-attendance/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthEventsIndexRoute = AuthEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEventsEventIdIndexRoute = AuthEventsEventIdIndexRouteImport.update({
  id: '/events/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthAdminIndexRoute
  '/events': typeof AuthEventsIndexRoute
  '/office-attendance': typeof AuthOfficeAttendanceIndexRoute
  '/profile': typeof AuthProfileIndexRoute
  '/rooms': typeof AuthRoomsIndexRoute
  '/login': typeof UnauthLoginIndexRoute
  '/password-reset': typeof UnauthPasswordResetIndexRoute
  '/register': typeof UnauthRegisterIndexRoute
  '/events/$eventId': typeof AuthEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthAdminIndexRoute
  '/events': typeof AuthEventsIndexRoute
  '/office-attendance': typeof AuthOfficeAttendanceIndexRoute
  '/profile': typeof AuthProfileIndexRoute
  '/rooms': typeof AuthRoomsIndexRoute
  '/login': typeof UnauthLoginIndexRoute
  '/password-reset': typeof UnauthPasswordResetIndexRoute
  '/register': typeof UnauthRegisterIndexRoute
  '/events/$eventId': typeof AuthEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_unauth': typeof UnauthRouteRouteWithChildren
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/events/': typeof AuthEventsIndexRoute
  '/_auth/office-attendance/': typeof AuthOfficeAttendanceIndexRoute
  '/_auth/profile/': typeof AuthProfileIndexRoute
  '/_auth/rooms/': typeof AuthRoomsIndexRoute
  '/_unauth/login/': typeof UnauthLoginIndexRoute
  '/_unauth/password-reset/': typeof UnauthPasswordResetIndexRoute
  '/_unauth/register/': typeof UnauthRegisterIndexRoute
  '/_auth/events/$eventId/': typeof AuthEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/events'
    | '/office-attendance'
    | '/profile'
    | '/rooms'
    | '/login'
    | '/password-reset'
    | '/register'
    | '/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/events'
    | '/office-attendance'
    | '/profile'
    | '/rooms'
    | '/login'
    | '/password-reset'
    | '/register'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_unauth'
    | '/_auth/admin/'
    | '/_auth/events/'
    | '/_auth/office-attendance/'
    | '/_auth/profile/'
    | '/_auth/rooms/'
    | '/_unauth/login/'
    | '/_unauth/password-reset/'
    | '/_unauth/register/'
    | '/_auth/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  UnauthRouteRoute: typeof UnauthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauth': {
      id: '/_unauth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauth/register/': {
      id: '/_unauth/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof UnauthRegisterIndexRouteImport
      parentRoute: typeof UnauthRouteRoute
    }
    '/_unauth/password-reset/': {
      id: '/_unauth/password-reset/'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof UnauthPasswordResetIndexRouteImport
      parentRoute: typeof UnauthRouteRoute
    }
    '/_unauth/login/': {
      id: '/_unauth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthLoginIndexRouteImport
      parentRoute: typeof UnauthRouteRoute
    }
    '/_auth/rooms/': {
      id: '/_auth/rooms/'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AuthRoomsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/profile/': {
      id: '/_auth/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/office-attendance/': {
      id: '/_auth/office-attendance/'
      path: '/office-attendance'
      fullPath: '/office-attendance'
      preLoaderRoute: typeof AuthOfficeAttendanceIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/events/': {
      id: '/_auth/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthEventsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/events/$eventId/': {
      id: '/_auth/events/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AuthEventsEventIdIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
  AuthEventsIndexRoute: typeof AuthEventsIndexRoute
  AuthOfficeAttendanceIndexRoute: typeof AuthOfficeAttendanceIndexRoute
  AuthProfileIndexRoute: typeof AuthProfileIndexRoute
  AuthRoomsIndexRoute: typeof AuthRoomsIndexRoute
  AuthEventsEventIdIndexRoute: typeof AuthEventsEventIdIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthEventsIndexRoute: AuthEventsIndexRoute,
  AuthOfficeAttendanceIndexRoute: AuthOfficeAttendanceIndexRoute,
  AuthProfileIndexRoute: AuthProfileIndexRoute,
  AuthRoomsIndexRoute: AuthRoomsIndexRoute,
  AuthEventsEventIdIndexRoute: AuthEventsEventIdIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface UnauthRouteRouteChildren {
  UnauthLoginIndexRoute: typeof UnauthLoginIndexRoute
  UnauthPasswordResetIndexRoute: typeof UnauthPasswordResetIndexRoute
  UnauthRegisterIndexRoute: typeof UnauthRegisterIndexRoute
}

const UnauthRouteRouteChildren: UnauthRouteRouteChildren = {
  UnauthLoginIndexRoute: UnauthLoginIndexRoute,
  UnauthPasswordResetIndexRoute: UnauthPasswordResetIndexRoute,
  UnauthRegisterIndexRoute: UnauthRegisterIndexRoute,
}

const UnauthRouteRouteWithChildren = UnauthRouteRoute._addFileChildren(
  UnauthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  UnauthRouteRoute: UnauthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
